SELECT 
	RESTAURANTS.SIFR AS RESTAURANTID,
	CASHGROUPS.SIFR AS CASHGROUPID,
	VISITS.SIFR AS VISITID,
	PRINTCHECKS.STARTDATETIME AS CHECKOPEN,
	PRINTCHECKS.CLOSEDATETIME AS CHECKCLOSE,
	VISITS.STARTTIME AS VISITSTARTTIME,
	PRINTCHECKS.PRINTNUMBER AS ORDERNUM,
	PRINTCHECKS.FISCDOCNUMBER AS FISCDOCNUM,
	ORDERS.PRICELISTSUM  AS ORDERSUM,
	PRINTCHECKS.FISCALSUM AS PAYSUM,
	ORDERS.TOTALDISHPIECES AS ITEMCOUNT,
	PAYM.PAYLINETYPE AS PAYMETHOD,
	0 AS BONUSSUM,
	'' AS BONUSCOMMENT
FROM PRINTCHECKS
LEFT JOIN CASHGROUPS on CASHGROUPS.SIFR = PRINTCHECKS.MIDSERVER
LEFT JOIN RESTAURANTS on RESTAURANTS.SIFR = CASHGROUPS.RESTAURANT
LEFT JOIN VISITS on VISITS.SIFR = PRINTCHECKS.VISIT
LEFT JOIN ORDERS on ORDERS.VISIT = PRINTCHECKS.VISIT AND ORDERS.MIDSERVER = PRINTCHECKS.MIDSERVER
LEFT JOIN (
	SELECT
		PAYMENTS.VISIT,
		PAYMENTS.MIDSERVER,
		PAYMENTS.PAYLINETYPE
	FROM PAYMENTS
	GROUP BY
		PAYMENTS.VISIT,
		PAYMENTS.MIDSERVER,
		PAYMENTS.PAYLINETYPE
) AS PAYM ON PAYM.VISIT =  PRINTCHECKS.VISIT AND PAYM.MIDSERVER =  PRINTCHECKS.MIDSERVER
WHERE 
	PRINTCHECKS.CLOSEDATETIME BETWEEN {{DATE_FROM}} AND {{DATE_TO}}
{{FILTER}}
ORDER BY PRINTCHECKS.CLOSEDATETIME ASC
OFFSET {{FROM}} ROWS
FETCH NEXT {{COUNT}} ROWS ONLY
