SELECT 
	RESTAURANTS.SIFR AS RESTAURANTID,
	CASHGROUPS.SIFR AS CASHGROUPID,
	VISITS.SIFR AS VISITID,
	PRINTCHECKS.STARTDATETIME AS CHECKOPEN,
	PRINTCHECKS.CLOSEDATETIME AS CHECKCLOSE,
	VISITS.STARTTIME AS VISITSTARTTIME,
	PRINTCHECKS.PRINTNUMBER AS ORDERNUM,
	PRINTCHECKS.FISCDOCNUMBER AS FISCDOCNUM,
	ORDERS.PRICELISTSUM  AS ORDERSUM,
	SUM(PAYBINDINGS.PAYSUM) AS PAYSUM,
	ORDERS.TOTALDISHPIECES AS ITEMCOUNT,
	PAYM.PAYLINETYPE AS PAYMETHOD,
	0 AS BONUSSUM,
	'' AS BONUSCOMMENT
FROM PRINTCHECKS
LEFT JOIN CASHGROUPS ON CASHGROUPS.SIFR = PRINTCHECKS.MIDSERVER
LEFT JOIN RESTAURANTS ON RESTAURANTS.SIFR = CASHGROUPS.RESTAURANT
LEFT JOIN VISITS ON VISITS.SIFR = PRINTCHECKS.VISIT
LEFT JOIN ORDERS ON ORDERS.VISIT = PRINTCHECKS.VISIT AND ORDERS.MIDSERVER = PRINTCHECKS.MIDSERVER
LEFT JOIN CURRLINES ON CURRLINES.VISIT = PRINTCHECKS.VISIT AND CURRLINES.MIDSERVER = PRINTCHECKS.MIDSERVER AND CURRLINES.CHECKUNI = PRINTCHECKS.UNI 
LEFT JOIN PAYBINDINGS ON PAYBINDINGS.VISIT = PRINTCHECKS.VISIT AND PAYBINDINGS.MIDSERVER = PRINTCHECKS.MIDSERVER AND PAYBINDINGS.CURRUNI = CURRLINES.UNI
LEFT JOIN (
	SELECT
		PAYMENTS.VISIT,
		PAYMENTS.MIDSERVER,
		PAYMENTS.PAYLINETYPE
	FROM PAYMENTS
	GROUP BY
		PAYMENTS.VISIT,
		PAYMENTS.MIDSERVER,
		PAYMENTS.PAYLINETYPE
) AS PAYM ON PAYM.VISIT =  PRINTCHECKS.VISIT AND PAYM.MIDSERVER =  PRINTCHECKS.MIDSERVER
WHERE 
	PRINTCHECKS.CLOSEDATETIME BETWEEN {{DATE_FROM}} AND {{DATE_TO}}
	AND PAYBINDINGS.STATE = 6
{{FILTER}}
GROUP BY
	RESTAURANTS.SIFR,
	CASHGROUPS.SIFR,
	VISITS.SIFR,
	PRINTCHECKS.STARTDATETIME,
	PRINTCHECKS.CLOSEDATETIME,
	VISITS.STARTTIME,
	PRINTCHECKS.PRINTNUMBER,
	PRINTCHECKS.FISCDOCNUMBER,
	ORDERS.PRICELISTSUM,
	ORDERS.TOTALDISHPIECES,
	PAYM.PAYLINETYPE
ORDER BY PRINTCHECKS.CLOSEDATETIME ASC
OFFSET {{FROM}} ROWS
FETCH NEXT {{COUNT}} ROWS ONLY
